default:
  image: node:16.16.0

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$CI_SECRET_DEPLOY_KEY
    - vercel build --token=$CI_SECRET_DEPLOY_KEY
    - vercel deploy --prebuilt  --token=$CI_SECRET_DEPLOY_KEY

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$CI_SECRET_DEPLOY_KEY
    - vercel build --prod --token=$CI_SECRET_DEPLOY_KEY
    - vercel deploy --prebuilt --prod --token=$CI_SECRET_DEPLOY_KEY
