default:
  image: node:16.16.0

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=IVs8fhoon4uqKIazAJ142vmm
    - vercel build --token=IVs8fhoon4uqKIazAJ142vmm
    - vercel deploy --prebuilt  --token=IVs8fhoon4uqKIazAJ142vmm

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=IVs8fhoon4uqKIazAJ142vmm
    - vercel build --prod --token=IVs8fhoon4uqKIazAJ142vmm
    - vercel deploy --prebuilt --prod --token=IVs8fhoon4uqKIazAJ142vmm